### ISSUE TITLE
@ahans as a maintainer?

### ISSUE THREAD

**Issue by iHiD** [exercism/c#1010]
@ahans 👋  

You've passed the threshold to become a maintainer of this track. Would you be happy to be appointed? 

Thanks!

**Comment by ahans** [comment]
> You've passed the threshold to become a maintainer of this track. Would you be happy to be appointed? 

Thanks! What exactly would be expected from me?

**Comment by ErikSchierboom** [comment]
Nothing more than what you were already doing basically :) Are you still interested?

**Comment by ahans** [comment]
> Nothing more than what you were already doing basically :) Are you still interested?

That sounds good! Then sign me up please! :smile:

**Comment by ErikSchierboom** [comment]
Awesome. Thank you!

You should receive an invite to join the org and the team now. You'll also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)
