### ISSUE TITLE
Add an explanation of example.c/h to README

### ISSUE THREAD

**Issue by patricksjackson** [exercism/c#103]
The main contributing guide explains a little about how example solutions work across the Exercism tracks, but the usage here of example.c, example.h, and the provided headers should be explicitly explained in our README.

The same patch would likely apply to the exercism/xcpp repo as well.

**Comment by wolf99** [comment]
Should this have been protected from the probot?

**Comment by ryanplusplus** [comment]
You're right, I think we should keep this open.
