### ISSUE TITLE
indent.sh not working

### ISSUE THREAD

**Issue by wolf99** [exercism/c#151]
The `./indent.sh` script seems to have stopped working. The output after executing is

    : not found: 5: ./indent.sh:
    ./indent.sh: 6: ./indent.sh: Syntax error: word unexpected (expecting "do")

This is due to the CRLF line-endings present in the file which you can see as `0d 0a` if you run `$ hexdump -C ./indent.sh`:

```
00000000  23 21 2f 62 69 6e 2f 73  68 0d 0a 23 0d 0a 23 20  |#!/bin/sh..#..# |
00000010  49 6e 64 65 6e 74 73 20  61 6c 6c 20 2e 63 20 61  |Indents all .c a|
00000020  6e 64 20 2e 68 20 66 69  6c 65 73 20 69 6e 20 74  |nd .h files in t|
00000030  68 65 20 70 72 6f 6a 65  63 74 20 74 68 61 74 20  |he project that |
00000040  61 72 65 20 6e 6f 74 20  76 65 6e 64 6f 72 20 63  |are not vendor c|
00000050  6f 64 65 20 28 69 65 3a  20 55 6e 69 74 79 29 2e  |ode (ie: Unity).|
00000060  0d 0a 23 0d 0a 0d 0a 66  6f 72 20 66 20 69 6e 20  |..#....for f in |
00000070  24 28 66 69 6e 64 20 65  78 65 72 63 69 73 65 73  |$(find exercises|
00000080  2f 20 2d 6e 6f 74 20 2d  70 61 74 68 20 27 2a 2f  |/ -not -path '*/|
00000090  76 65 6e 64 6f 72 2f 2a  27 20 2d 6e 61 6d 65 20  |vendor/*' -name |
000000a0  27 2a 2e 63 27 20 2d 6f  72 20 2d 6e 6f 74 20 2d  |'*.c' -or -not -|
000000b0  70 61 74 68 20 27 2a 2f  76 65 6e 64 6f 72 2f 2a  |path '*/vendor/*|
000000c0  27 20 2d 6e 61 6d 65 20  27 2a 2e 68 27 29 3b 20  |' -name '*.h'); |
000000d0  64 6f 0d 0a 20 20 69 6e  64 65 6e 74 20 2d 6e 62  |do..  indent -nb|
000000e0  61 64 20 2d 62 61 70 20  2d 6e 62 63 20 2d 62 62  |ad -bap -nbc -bb|

```

These can be removed either by editing the file or running `$ cat ./indent.sh | tr -d '\r' >> ./indent_new.sh`

Not sure if there is a reason this hasn't shown up until now? Maybe the issue is only present on my machine for some reason?

**Comment by ryanplusplus** [comment]
I'm not able to reproduce this on MacOS Sierra. I can try on Ubuntu tonight. Is there any chance that this is because of how you've configured git? Specifically, see the `autocrlf` option here: https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration.

**Comment by patricksjackson** [comment]
Works fine on Linux as well (using the WSL). That file has never been altered, so if it _stopped_ working then it must be your settings @wolf99

**Comment by wolf99** [comment]
Ah, that could be it @ryanplusplus, good call. I have git in powershell (which likely has autocrlf set) and another git in WSL (which probably doesn't have autocrlf set) so I probably pulled with the wrong one. Thanks both.
