### ISSUE TITLE
Hello World does not follow canonical example

### ISSUE THREAD

**Issue by Gamecock** [exercism/c#177]
I this exchange on gitter.
```
B Krishnan Iyer @krish-iyer Sep 21 12:50
yup
you know what this is toughest hello-world programme
I ever came across
and after completing this I can proudly say no matter what people think

Norbert Melzer @NobbZ Sep 21 12:53
Yeah… It's still using an old version of the exercise… And if the newer version were implemented it might be much easier.
```
Cannonical representation is [here](https://github.com/exercism/problem-specifications/blob/master/exercises/hello-world/canonical-data.json)

**Comment by ryanplusplus** [comment]
I'm all for this. We went through a prior round of simplification previously in order to eliminate some unnecessary obstacles: https://github.com/exercism/c/issues/56

By the way, was that snippet in reference to this track or to some other track?

**Comment by Gamecock** [comment]
It was in reference to the c track.

**Comment by patricksjackson** [comment]
Yes, my feelings from that old thread are still true too :)

Thanks for bringing this up @Gamecock
