### ISSUE TITLE
Config has exercises with null predessessors

### ISSUE THREAD

**Issue by Gamecock** [exercism/c#181]
[config.json](https://github.com/exercism/c/blob/master/config.json) has the following non-core exercises with ` "unlocked_by": null,`.  leap & raindrops

Looking at cpp [config.json](https://github.com/exercism/cpp/blob/master/config.json) that may be irrelevant.

**Comment by wolf99** [comment]
Looking at https://github.com/exercism/docs/blob/master/language-tracks/configuration/track.md, I'm not sure which bit of the  "json at the end" you think is malconfigured? It seems OK to me

````
    {
      "uuid": "55b87cc2-c3a0-438a-b2b6-116ad6356802",
      "slug": "react",
      "core": false,
      "unlocked_by": "atbash-cipher",
      "difficulty": 10,
      "topics": [
        "memory management",
        "Functions"
      ] <-Ends 'topics' array of strings
    } <-Ends exercise object
  ], <-Ends 'exercises' array of exercise objects
  "foregone": [ <-Start 'forgone' array of  strings

  ] <-End 'forgone' array of strings
} <-End of JSON
````

**Comment by Gamecock** [comment]
You are right, I was overly tired when I looked at it.

**Comment by ryanplusplus** [comment]
@wolf99 it's related to Exercism v2. It's live as a demo/beta: https://v2.exercism.io/

**Comment by Gamecock** [comment]
@ryanplusplus I notice the C track is not on v2, what do we need to do to make it work.  I'm happy to  do some work, but I don't know what needs done?

**Comment by Gamecock** [comment]
per [discussion #175](https://github.com/exercism/discussions/issues/175) having null prereqs on some excercises is a requirement.  Someone with  the right authority please close this issue.

**Comment by ryanplusplus** [comment]
@Gamecock I think we probably just need to officially launch to get on v2 but I am not sure.

**Comment by patricksjackson** [comment]
Yea, the C track isn't there only because it isn't officially launched.
