### ISSUE TITLE
all: Naming style inconstencies

### ISSUE THREAD

**Issue by NobbZ** [exercism/c#184]
I'm randomly doing some of the C exercises and I realised, that some do use camelCase, others snake_case for the functions to implement.

Is there a certain reason for this inconsistency or is a PR uniforming those welcome? If yes, should it favor snake_case or camelCase?

**Comment by ryanplusplus** [comment]
A PR would absolutely be welcome. We're trying to adhere to the [Linux kernel coding style](https://www.kernel.org/doc/html/v4.10/process/coding-style.html) which uses snake case, so snake case should be favored.

**Comment by sjwarner-bp** [comment]
I'd be interested in trying to do this. I might just pick up one exercise with the inconsistency and issue a PR just to make sure that I've got the right idea, then do a few more if that is ok?

**Comment by wolf99** [comment]
@ryanplusplus this would probably be a good candidate for the "good first commit" label

**Comment by sjwarner-bp** [comment]
Please ignore that reference and pull request! I will try again.

**Comment by sjwarner-bp** [comment]
I think that PR was ok. Please let me know if I have done anything wrong, otherwise I will look to fix up a few more of these exercises. Sorry for the clutter above!

**Comment by wolf99** [comment]
@sjwarner-bp , this issue as currently stated is for 

> the functions to implement

That is, the functions that the student see's in the interface implied by the tests (and possibly the header), i.e. "public" functions. In the PR #185 you have changed the name for a `static` function. While it might be good style to have *all* functions named consistently, I'm not sure that this is what this issue was aimed at. Maybe @NobbZ could clarify on that point?

Further it would maybe be better to have this work for all exercises done under a single PR, rather than a PR per exercise... might wait for word from @ryanplusplus  or @patricksjackson though 😃

**Comment by NobbZ** [comment]
The name of the FUTs is probably the first name in each suites that a student sees. And I found different naming schemes a bit confusing.

In #185 only the example implementation was changed, while the tests would still try call `getVerse`. So basically, things that needs to get changed are stubs (for exercises which have them), tests, and the example code.

For me, beeing consistent with the names of the FUTs is the most important part. If though actual test names follow the same conventions that would be a plus.

---

FUT: Function under test

**Comment by sjwarner-bp** [comment]
I agree, though they were static methods it still probably wants to be consistent to avoid confusion.

I only changed the implementation as I couldn't see calls to that method in the tests (I could only see tests that referenced the two functions the student should implement). I'd be happy to update that if anyone could highlight to me where I'd missed my updates out!

**Comment by sjwarner-bp** [comment]
@wolf99 Yes, I also wondered about variables etc, as it does look a little odd! But I wasn't sure so didn't touch them. Maybe I'll do some extra reading on the Linux kernel coding style :smile:

**Comment by wolf99** [comment]
@sjwarner-bp FYI I'm not overly familiar with the kernal style, I simply looked at what all the code samples seemed to use and at a cursory search through the linked document I didn't find any specific rule either way on this.

**Comment by ryanplusplus** [comment]
Hey guys, sorry, busy day.

@wolf99 yes, I think we should go snake case on functions (static and global), parameters, variables etc. I think this consistency will be good all around because we're not indicating anything meaningful by changing style.

Additionally, I think one PR per exercise is probably the right way to attack it. It's definitely much easier for me to follow bite-sized PRs and also makes for much more quickly merged PRs :).

**Comment by Gamecock** [comment]
Should we snake case the variable names also?

**Comment by wolf99** [comment]
@gamecock I think that is what Ryan meant by:

>I think we should go snake case on functions (static and global), parameters, variables etc

Looking at some exercise that already conforms can confirm this for us. The acronym exercise is a good example. In that exercise, *everything* is snake cased or uses a single (but descriptive) word: function names, parameter names, variable names, test names, etc; the whole caboodle.

**Comment by wolf99** [comment]
Looking at some other examples, another question arises with regards to consistency. Some examples do use snake case but use capital letters `Like_This` or even mixed like `Alergen_List_t` is there a determination on which is expected and if it is lower case (as I had thought previously), should these upper cased ones also be updated?

**Comment by wolf99** [comment]
List of exercises that use some, or all, non-snake cased names:
- [x] all-your-base
- [x] beer-song
- [ ] isogram
- [ ] meetup
- [ ] palindrome-products
- [ ] robot-simulator
- [ ] series
- [ ] sieve
- [ ] word-count

**Comment by ryanplusplus** [comment]
@wolf99 my interpretation of the Linux kernel style is that we should be using lower snake case. I perused a few modules and found nothing to convince me otherwise. Let's go with that.

**Comment by Gamecock** [comment]
I'll get series and meetup as part of #187

**Comment by wolf99** [comment]
@sjwarner-bp Are you still working to update beer-song?

**Comment by wolf99** [comment]
Think that's this issue's work complete now.

**Comment by ryanplusplus** [comment]
@wolf99 I think there are more non-caps enums that we can take care of on this ticket.

**Comment by Gamecock** [comment]
- [ ] Allergies

- [ ] Perfect Numbers

- [ ] React

- [ ] Robot Simulator

- [ ] Space Age

**Comment by Gamecock** [comment]
I have allergies

**Comment by wolf99** [comment]
While doing the enum case changes I've noticed one or two `const` variables that are not all caps. I'll compile a list of the exercises that this occurs in shortly.

**Comment by Gamecock** [comment]
I I think we can close this, after digging through the linux kernel I don't see any examples of a variable declared as const in all caps, and did find one [global](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/module.c?h=v4.14-rc5) in lower_snake_case.  It appears UPPER_SNAKE_CASE is reserved for #defines and enums.

```
static const struct latch_tree_ops mod_tree_ops = {
	.less = mod_tree_less,
	.comp = mod_tree_comp,
};
```

**Comment by ryanplusplus** [comment]
Perfect, thanks for checking @Gamecock
