### ISSUE TITLE
Sum Of Multiples needs additional cases

### ISSUE THREAD

**Issue by Gamecock** [exercism/c#188]
Add test cases for null ptrs (requires testing with a null pointer with non-zero length), divide by zero.

**Comment by patricksjackson** [comment]
Just so I understand, you want to add a test for deceptive input?

**Comment by Gamecock** [comment]
I'd prefer the the term `malformed` or `erroneous`  vs `deceptive` because they don't imply intent, but that's the general idea.
@wolf99  added the check for `multiple of zero` to his solution.

and binary search has these two tests which seem useful.  Although maybe only absolutely need the second.
```void test_empty_array(void)
{
   TEST_IGNORE();
   int *arr = NULL;
   size_t length = 0;
   TEST_ASSERT_EQUAL_PTR(NULL, binary_search(1, arr, length));
}

void test_zero_length_array(void)
{
   TEST_IGNORE();
   int arr[] = { 1 };
   size_t length = 0;
   TEST_ASSERT_EQUAL_PTR(NULL, binary_search(1, arr, length));
}
```

**Comment by wolf99** [comment]
Such tests could be helpful in terms of learning edge cases. Though they would require minimal extra work from a learner (as a well coded solution should pass such tests anyway), they do lead into the edge case checks for perfect-numbers (which is obviously a thematic successor to sum-of-multiples).
