### ISSUE TITLE
Add a style guide document for exercises

### ISSUE THREAD

**Issue by wolf99** [exercism/c#209]
With #184 nearing completion it might be handy to add a short style guide to the repository's documentation. 

I note that the README mentions Linux kernel style, as we have aimed for here, but as far as I can tell (being unfamiliar with Linux development), that guide does not mention the issues we have looked at on #184. Things such as name casing for names (all-lower case snake case), enums (all-caps snake case), consts (all-caps snake case), etc

Such a document should be kept short, no need to reiterate what *is* already on the Linux kernel guide, simply reference that, then add any missing points. The document can then be referenced from the README.

Worthwhile?

EDIT: Just to clarify, the guide would apply to execises within the repository, not aimed at exercise submissions!

**Comment by ryanplusplus** [comment]
Worthwhile. The kernel style guide implies some of the naming rules (ie: they have to be gleaned from code samples) and is also pretty long. I think that having a short summary of what we took from it would make it easier for contributors.

**Comment by wolf99** [comment]
Working on this in #217 then 😃

**Comment by wolf99** [comment]
And closed by #217 merge
