### ISSUE TITLE
TESTS.md has empty sections

### ISSUE THREAD

**Issue by wolf99** [exercism/c#230]
The [TESTS.md](https://github.com/exercism/c/blob/master/docs/TESTS.md) documentation file has sections on testing on Linux, on Windows with Visual Studio and on Mac with Xcode. The latter two sections are empty however.

I think this is one of the final asks for documentation for launching the track so it would be good to get these sections filled out.

Does anyone have information on testing exercises with Xcode or Visual Studio that they could contribute here?

If these environments only require the information already contained in the document (i.e. Select 'build' from the relevant menu) then we could rejig the current information a little better instead.

**Comment by wolf99** [comment]
I have experimented a small bit now with VS 2017. Using @patricksjackson's method of creating a "Blank Project" template and adding all example files, I can build, run and debug an exercise. Note though that this method does not use the makefile at all and instead relies on VS to work its magic on automatically linking everything that might be needed. This also means there is no separate `make` and `make test`.

It is very simple to use once the files are added to the project though. To build just _Build > Build Solution_ (or _Ctrl + Shift + B_), to debug/run just _Debug > Start Debugging_ ( or _F5_).

[This](https://docs.microsoft.com/en-gb/cpp/ide/non-msbuild-projects) seems to be the current documentation on using non-MSBuild projects in VS. It looks like it borrows heavily from VS-Code JSON-type settings files, but I have little experience (or patience 😄) for that at the moment.

**Comment by ryanplusplus** [comment]
No (recent) experience with Xcode directly, but on a Mac it's easy enough to do exactly what you do on Linux once you've got Xcode (and the command line tools) installed. I think we could probably skip setup within Xcode and defer to the terminal on OS X.

**Comment by wolf99** [comment]
@ryanplusplus  That sounds easier. 

In that regard, should we consider changing advice entirely from using VS to using a Linux distro in WSL to build and test? With the Windows OS Fall Creators Update (v1709) the WSL is out of beta on MS and also no longer requires developer mode to be enabled.

The advantage here being that this would make all instructions very similar and thus easier to support and maintain. The current VS information might be kept for those that would still like to edit, debug, etc in an IDE, but would not be the _recommended_ path.

**Comment by ryanplusplus** [comment]
@wolf99 that's what I would do if I were using Windows. @patricksjackson is more familiar with development on Windows and so may have a different perspective.

**Comment by wolf99** [comment]
Closed by #236
