### ISSUE TITLE
Complex Numbers: Final test case appears incorrect

### ISSUE THREAD

**Issue by gfrans** [exercism/c#256]
https://github.com/exercism/c/blob/master/exercises/complex-numbers/README.md
https://github.com/exercism/problem-specifications/blob/master/exercises/complex-numbers/canonical-data.json

Based on the description in the readme, it sounds like the ```c_exp()``` function is supposed to find the natural log of a complex number (its exponent, base __e__).  But the test cases imply it's meant to find the value of __e__ raised to a complex number.  Can someone clarify which is intended?  The confusion mostly stems from my lack of understanding of the subject... my apologies.

**Comment by wolf99** [comment]
I am unsure myself but, @clementi might have info there as he implemented the exercise.

**Comment by clementi** [comment]
The `c_exp` function is intended to compute the result of raising _e_ to a complex number, or _e^z_.

**Comment by wolf99** [comment]
Possibly an issue should be raised on the problem specifications repo to clarify this point. IMHO the sentence in the README is rather unclear.

**Comment by wolf99** [comment]
Have recommended that the related issue on the problem-specification issue be put up for good-first-patch. Once it gets changed there it can get pulled in here to match.
