### ISSUE TITLE
Is it safe to delete the stale branches?

### ISSUE THREAD

**Issue by wolf99** [exercism/c#258]
There are currently two stale branches in this repository. Simply in the interests of cleaning up (and being a tad OCD) I looked to see if the stale branches could be removed.

- ignore-key : Has four commits and looks to be fast-forward merged with master.
- stray-x-refs : Has two commits. The first (7151cf3) appears to have been cherry-picked or otherwise copied onto master (f5e932c). I can't determine where the second (612a623) made it onto master but the change _is_ currently present on master.

I can't see any reason why either would be unsafe to remove but wanted to double check.

**Comment by kytrinyx** [comment]
I can't remember what I was doing with those :) I'm sure I had a plan at some point. If it's important I'll recreate them from scratch.
