### ISSUE TITLE
Exercise versioning

### ISSUE THREAD

**Issue by wolf99** [exercism/c#261]
I don't think the exercises here include any information about which version of the canonical-data they conform to. This can make it hard to know which or what needs updating, particularly with the rapid pace of the problem-specifications repo.

There was recent discussion about data/track consistency on [https://github.com/exercism/problem-specifications/issues/524](https://github.com/exercism/problem-specifications/issues/524) and all the other issues linked therein.

- Should we add some record of the version each exercise conforms to? (such that it is apparent to repository viewers, not necessarily students)
- Does anyone have any suggestion on the best way to approach implementing this?

**Comment by kotp** [comment]
In the Ruby track, we used a constant that indicated the version, that the student would set.  When we read the submission, we would know what version of the test it is written for.

I believe this is going away in _Nexercism_ in favor of another way to track this.  And that will be a good thing.

**Comment by ryanplusplus** [comment]
My experience after having participated in tracks that both do and don't attempt to solve this problem is that the solution seems to serve to confuse people and/or add noise to submissions.

It seems to me to be a non-issue since the most likely to be viewed submissions are the most recent and the most likely users to view those submissions are users that just submitted their own. This means that the viewers are pretty likely to see solutions that match the test suite they used. Whenever I personally see a solution that is obviously from a different test suite, I will generally just ignore it and move on (unless it's pretty close). When a submission was written against a different version of the test suite, we don't really expose those different versions so I'd assume users just as likely as I am to simply ignore them and move on.

@kotp do you have a link to the discussion for Nextercism? I'm curious what solutions have been proposed. Perhaps tying the solution to the test suite in a more concrete way so that the test suite can be served along with the solution?

**Comment by ryanplusplus** [comment]
Sorry @wolf99 I lost your the thread of your comment after reading @kotp's comment. I see now that you're talking about keep in sync with "upstream", not trying to expose this to students. My comment is in regards to exposing this to students/reviewers.

**Comment by kotp** [comment]
Not offhand, though months ago, @kytrinyx had suggested that we would be able to do away with that.  In the Ruby track, there is a version indicator based on (I believe) sha's from git commits that indicate the versioning.

It looks something like:

```plain
# Common test data version: 1.0.1 196fc1a
```

That is pulled from the anagram exercise I have sitting locally, via `exercism fetch`.

**Comment by wolf99** [comment]
Yes, I'd very much imagine that for the C track this (at least initially) should be something very simple and implemented in such a manner that it would not change the way students currently use the C track.

@kotp  I also would be interested in what is being planned in this regard for nextercism - there isn't much point in us putting a lot of work in on this here only to be made redundant by nextercism. Further I am unaware if there is a timeline for release of nextercism, which makes it a little unclear as to how to balance how much work here would be too much or not enough. 

Manually divining which exercises need updating currently just relies on students noticing problems and then maintainers noticing that the canonical data has already fixed such, so this is already some level of work that could be reduced by implementing something in the more immediate future if nextercism is still some distance off.

**Comment by kotp** [comment]
> Yes, I'd very much imagine that for the C track this (at least initially) should be something very simple

It may be worthwhile doing for the reasons that you stated... and for the "exercise of it".

Especially if it ends up being a gateway for a first time contributor with the C track... they will likely feel more comfortable making future contributions in the project.  And in the meantime, you end up with a benefit until Nextercism.

**Comment by wolf99** [comment]
Seems like there is some discussion about this in `common`, with several approaches being put forth.

https://github.com/exercism/meta/issues/97
https://github.com/exercism/discussions/issues/133
https://github.com/exercism/problem-specifications/issues/524

behrtam mentions a python tool in 133 linked above, PeterTseng also mentions a ruby tool in the same issue.

**Comment by ryanplusplus** [comment]
I like the solution in https://github.com/exercism/meta/issues/97. Fingers crossed!

**Comment by wolf99** [comment]
Yes - the benefit there is that the resulting issues would be very eligible for the good-first-patch label and also would require no change to the existing tools and code. Fingers-crossed++

**Comment by wolf99** [comment]
Seems like the work in https://github.com/exercism/meta/issues/97 ended up not progressing..I will comment on that thread soon to ask if Katrina received anything but otherwise I may start investigating this a little more again myself.

**Comment by kytrinyx** [comment]
I'm going to close that issue and re-open a fresh one that doesn't reference RailsGirls summer of code, since there is no selected team to work on it this summer.

**Comment by kytrinyx** [comment]
The new issue is open in https://github.com/exercism/meta/issues/99

**Comment by wolf99** [comment]
I believe this is solved by #487 ?

**Comment by ryanplusplus** [comment]
> I believe this is solved by #487 ?

I agree
