### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by stsewd** [exercism/c#291]
The `The Definitive C Book Guide and List: The legendary StackOverflow's question about C books.` link gives a 404 https://stackoverflow.com/questions/562303/the-definitive-c-book-guide-and-list

Thi is on https://github.com/exercism/c/blob/master/docs/RESOURCES.md

**Comment by ryanplusplus** [comment]
Thanks. It looks like a SO moderator removed it: https://stackoverflow.com/questions/562303/the-definitive-c-book-guide-and-list/562362
