### ISSUE TITLE
Tests.md instructions update (Build your code section)

### ISSUE THREAD

**Issue by mikewalker** [exercism/c#317]
After doing this for each exercise I think we should add a line to the build your code section of tests.md. Currently we say to issue the command touch src/bob.{h,c}. If you do that without first creating the src directory you get errors (at least on Fedora 28).

touch: cannot touch 'src/bob.h': No such file or directory
touch: cannot touch 'src/bob.c': No such file or directory

Maybe just add "mkdir src (from the exercise directory) to the instructions right before the touch command? I just automatically create the directory for each new exercise, but for someone new it may be nice to be in the instructions.

**Comment by wolf99** [comment]
Thanks for raising this @mikewalker, along with the other issues you've raised recently they are some nice little QoL improvements! 💯

**Comment by mikewalker** [comment]
@wolf99 Your most welcome, I'm retired now but old habits die hard. After spending almost 25 years doing various roles in QA, the see a bug report it thing is part of my being now. lol
