### ISSUE TITLE
Format in readme and test don't agree

### ISSUE THREAD

**Issue by mikewalker** [exercism/c#328]
Doesn't this test violate the format outlined in the readme? Its the second one that I am referring to. Since the format is 

```text
(NXX)-NXX-XXXX
```
where `N` is any digit from 2 through 9 and `X` is any digit from 0 through 9.

So in this case after taking the country code away the number 1234567890 would be invalid since the first digit should be in the range [2..9].

```
void test_valid_when_11_digits_and_first_digit_is_1(void)
{
   const char input[] = "11234567890";
   const char expected[] = "1234567890";

   result = phone_number_clean(input);

   TEST_ASSERT_EQUAL_STRING(expected, result);
}
```

**Comment by ryanplusplus** [comment]
You're right, this was a mistake in the upstream test suite that was resolved in this commit: https://github.com/exercism/problem-specifications/commit/51d2475bba52b5ec7b02a4ff12ea42bc293888a5#diff-59f68d802e0ccde10042f386356a7c90. We need to update the tests for this track to reflect the current upstream test suite.

**Comment by mikewalker** [comment]
Thanks for for confirming, I was just working through the exercise and ran into this since my clean method went a bit further than this test was expecting. :)

**Comment by ryanplusplus** [comment]
No, thanks you. You must have great attention to detail to have found this!

**Comment by ryanplusplus** [comment]
If you're interested in making a contribution, the current upstream test suite is detailed here: https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json. If not, @wolf99 or I will make the change as we get some time (hopefully in the next few days).

**Comment by mikewalker** [comment]
I take it getting from the json file into the test suite is a manual process? I'll look into it, this would be my first PR so I may have questions. It does look pretty straight forward though.

**Comment by ryanplusplus** [comment]
Yes, it's a manual process. We're willing to answer questions :)

**Comment by mikewalker** [comment]
closing this since the PR was merged.
