### ISSUE TITLE
grains: Doesn't pass tests on 32 bits systems

### ISSUE THREAD

**Issue by jcirer** [exercism/c#332]
When I try to run the solution example for the grains exercise on a 32 bits linux system I get  this error:

```bash
make
Compiling tests.out
test/test_grains.c:14:test_square_1:FAIL: Unity 64-bit Support Disabled
test/test_grains.c:19:test_square_2:IGNORE
test/test_grains.c:25:test_square_3:IGNORE
test/test_grains.c:31:test_square_4:IGNORE
test/test_grains.c:37:test_square_16:IGNORE
test/test_grains.c:43:test_square_32:IGNORE
test/test_grains.c:49:test_square_64:IGNORE
test/test_grains.c:55:test_square_0_does_not_exist:IGNORE
test/test_grains.c:61:test_square_greater_than_64_does_not_exist:IGNORE
test/test_grains.c:67:test_total:IGNORE

-----------------------
10 Tests 1 Failures 9 Ignored 
FAIL
```

Thanks

**Comment by patricksjackson** [comment]
Try this:

Add `#define UNITY_SUPPORT_64` to the top of test_grains.c. The first few lines of the file should look like this (the order is important).

```
#define UNITY_SUPPORT_64
#include "vendor/unity.h"
#include "../src/grains.h"
```

If this works you'll need to add it to the other test files that use the Unity 64bit tests as well.

If it doesn't work, you should be able to just change all the calls to `TEST_ASSERT_EQUAL_UINT64` to `TEST_ASSERT_EQUAL`. This appears to be a deficiency in the test suite we're using.

**Comment by jcirer** [comment]
I tried to add `#define UNITY_SUPPORT_64`, but then it segfaults:

This is the output running `tests.out` in gdb:

```gdb
Program received signal SIGSEGV, Segmentation fault.
0x08048615 in UnityPrint (string=0x1 <error: Cannot access memory at address 0x1>) at test/vendor/unity.c:84
84	        while (*pch)
```

**Comment by patricksjackson** [comment]
Ok, did you try changing all the calls to `TEST_ASSERT_EQUAL_UINT64` to `TEST_ASSERT_EQUAL`?

**Comment by jcirer** [comment]
Yes, I changed to  `TEST_ASSERT_EQUAL(1ul, square(1));` and it segfaults with the same error and the same line.

**Comment by patricksjackson** [comment]
Sorry to be pedantic, but just to clarify since I may have been unclear, try it **without** the `#define UNITY_SUPPORT_64` and just change the ASSERT lines, so the only difference from the original is the change from `TEST_ASSERT_EQUAL_UINT64` to `TEST_ASSERT_EQUAL`.

Let me know if that doesn't work.

(Regardless, this is a deficiency in the unit test suite that we're using. Hopefully we can unblock you but we may need to take another look at fixing this some other way.)

**Comment by jcirer** [comment]
I'm sorry.

I left the `#define UNITY_SUPPORT_64` in `test/test_grains.c`. Without it, `example.c` compiles and passes the tests.

**Comment by patricksjackson** [comment]
I'm glad that worked!

You will hit this same issue in later tests, but you should be able to fix it the same way. Just make the same change I suggested here, and let us know if you have issues getting it to work.
