### ISSUE TITLE
Unity Test Suite doesn't work on 32-bit systems

### ISSUE THREAD

**Issue by patricksjackson** [exercism/c#334]
For some reason, Unity doesn't support 64-bit comparisons in a 32-bit binary, so all the `*_INT64/UINT64` test macros are just disabled. You can try it yourself by adding `-m32` to the compilation flags.

In #332 I pointed them to use the default compare, which casts everything to an int. It's not correct (since it casts what need to be 64bit values to 32bit) but it is the only workaround I could think of while keeping Unity.

Does anyone want to take a look at this? It seems like a problem if the test suite can't do that...

**Comment by ryanplusplus** [comment]
Can't we just use the generic `CHECK` macro in cases where we know we're comparing u64s? This doesn't give helpful output when a comparison fails, but it does sidestep this issue.

**Comment by patricksjackson** [comment]
Oh, right, that would have been a better fix. I would be hesitant to roll that out everywhere though because of the lack of helpful output.
