### ISSUE TITLE
Grains test constants are "ul" instead of "ull"

### ISSUE THREAD

**Issue by wiredancer** [exercism/c#339]
In the grains exercise, I routinely check that people use `unsigned long long` (or `uint64_t`) result types, so that tests won't fail if I execute them on a less-than-64 bit machine. Now I realized that test_grains.c declares all the expected results with the `ul` suffix - shouldn't this be `ull`?
At least on a 32 bit Ubuntu x86 machine which I checked, gcc implicitly interprets the larger numbers as 64 bit anyway, so they don't get truncated, and the tests do work correctly (i.e. they fail for solutions with unsigned long result type).

Do you agree that we should change the tests to use `ull`?

**Comment by wiredancer** [comment]
Yeah, its confusing with these historical type definitions. I usually recommend students to use the more readable <stdio.h> type definitions if size is important.

**Comment by ryanplusplus** [comment]
I agree. I work in the embedded space and stdint.h is a must.
