### ISSUE TITLE
Do you want to appear on the website

### ISSUE THREAD

**Issue by iHiD** [exercism/c#349]
@exercism/c I've noticed that none of you appear on the website because `show_on_website` is set to false [here](https://github.com/exercism/c/blob/master/config/maintainers.json). I just wanted to check that was deliberate :)

**Comment by ryanplusplus** [comment]
Thanks for the heads up. I've flipped mine to `true`.

**Comment by iHiD** [comment]
Yes. This is for maintainers. Mentoring is totally different. If you have been a maintainer, then you should be on the site (if you want to). If you're no longer active, you can be alumni. If you're still active, but busy with life, then you're still active and should be on the site :)

**Comment by wolf99** [comment]
Thanks for the info both, have flipped my status to `true`

**Comment by wolf99** [comment]
Pinging @patricksjackson and @RealBarrettBrown as may like to confirm they are happy with their status or change as appropriate

**Comment by patricksjackson** [comment]
I'm aware of that, so I might change it at some point. Thanks for the pointer.

I'm closing this since everyone's now seen it (or been pinged).
