### ISSUE TITLE
Is Gigasecond's solution as expected ?

### ISSUE THREAD

**Issue by QLaille** [exercism/c#350]
I've been "mentoring" several students doing the *Gigasecond* exercise, and each of their solutions can be resumed to a single line :

```c
time_t gigasecond_after(time_t t)
{
	return t + 1000000000;
}
```

Is this solution expected from maintainers ?

**Comment by ryanplusplus** [comment]
Yes, see https://github.com/exercism/c/blob/master/exercises/gigasecond/src/example.c. It is just a very easy exercise.
