### ISSUE TITLE
Improve the core track by making "Gigasecond" optional and instead making "Word Count" Core.

### ISSUE THREAD

**Issue by QLaille** [exercism/c#353]
It has been quite some time, that I can now say that every  gigasecond exercise I mentor is reduced to this: 
![image](https://user-images.githubusercontent.com/24566679/53481922-62d61b80-3a7e-11e9-80d8-ea84582bdc42.png)

I find it a bit cheap to have an exercise that doesn't let you learn much "Core", and would love instead to permute it with a "Side" exercise where implementations and solutions can differs, thus allowing more exchanges between tutor and students !

**Comment by ryanplusplus** [comment]
Sounds like a great idea. Would you mind making a pull request with these changes?
