### ISSUE TITLE
Word-count excessive words test case

### ISSUE THREAD

**Issue by sesamemucho** [exercism/c#359]
A fairly common error results in the solution accepting MAX_WORDS+1 words (the student makes a check ```index > MAX_WORD_COUNT``` instead of ```index >= MAX_WORD_COUNT```). The current test_excessive_number_words() has 23 words. It would be handy if this used 21 words instead, and so would catch this error.

**Comment by ryanplusplus** [comment]
Good catch. Would you mind creating a PR to make this change?

**Comment by sesamemucho** [comment]
OK

**Comment by patricksjackson** [comment]
Closing this since the PR that addressed it was merged.

(For future reference, Github will close the matching issue automatically once the PR is merged if you put in a phrase like "Closes #359" - https://help.github.com/en/articles/closing-issues-using-keywords)
