### ISSUE TITLE
ExitCode of failing tests indicate success

### ISSUE THREAD

**Issue by NobbZ** [exercism/c#364]
Currently, if I have a failing test, then the test suite will still exit with a `0` exitcode.

This makes it hard for me to incorporate my C solutions in my personal CI. CI for C will pass regardless if there are tests failing or not. The same problem does exist for running the tests on the track.

Unless there are compilation errors CI will always pass for this track.

Is there a way to indicate proper exit code from the testsuite?

**Comment by NobbZ** [comment]
After a short test, it seems to be enough to do changes equivalent to this one through all testsuites:

```diff
--- a/c/hamming/test/test_hamming.c
+++ b/c/hamming/test/test_hamming.c
@@ -92,6 +92,5 @@ int main(void)
    RUN_TEST(test_large_hamming_distance);
    RUN_TEST(test_hamming_distance_in_very_long_strand);

-   UnityEnd();
-   return 0;
+   return UnityEnd();
 }
```

**Comment by patricksjackson** [comment]
It turns out our CI for the track does properly see a test failure, since we are just grepping the output for "FAIL". I've fixed both issues.

Thanks!
