### ISSUE TITLE
Is -ts8 implied for GNU indent, and should it be used?

### ISSUE THREAD

**Issue by novakpetrovic** [exercism/c#366]
I recently resolved some issues I had with GNU `indent` on MSYS2.  In the process, I went (out of necessity!) through all options listed in [C_STYLE_GUIDE](https://github.com/exercism/c/blob/master/docs/C_STYLE_GUIDE.md), and noticed that `-linux` (in addition to other listed options) also has option `-ts8` (sets tab size to 8 spaces).  This is according to GNU `indent` version 2.2.12.  However, in the expanded equivalent list of options given in the style guide, option `-ts8` is not listed. This option is also not present in [indent.sh](https://github.com/novakpetrovic/c/blob/master/indent.sh).  I am not sure if it's a simple typo or there is a reason for not using it.

(1) Am I correct in saying that `-linux` does imply `-ts8`?
(2) If so, should `-ts8` be used when formatting _exercism_ C code? This means `-linux -i3 -nut` options are still valid. (This is probably the best solution.)
(3) Should `-ts3` be used instead?

While this is fairly trivial, since with `-ts8` a tab character is converted to 8 spaces (`-nut`) and then re-indented at 3 spaces due to `-i3`, I am raising it for another reason. I'd like to, later on, propose a small change to [indent.sh](https://github.com/novakpetrovic/c/blob/master/indent.sh), and would like to understand the background in order to avoid problems later on.

**Comment by patricksjackson** [comment]
Yes, `indent -linux` is equivalent to:

From: https://www.gnu.org/software/indent/manual/html_chapter/indent_1.html#SEC4
```
-nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4 
-cli0 -d0 -di1 -nfc1 -i8 -ip0 -l80 -lp -npcs -nprs -npsl -sai
-saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8 -il1
```

`-ts8` should do nothing in this codebase because we have `-i3 -nut` which replaces all tabs with 3 spaces. There isn't really a point in adding a tab size to the indent script AFAIK.

I believe the reason we don't use `indent -linux -i3 -nut` directly is due to the `-linux` option not being available on every system.

**Comment by ryanplusplus** [comment]
Hey @novakpetrovic, the primary reason for our current `indent` configuration is to match the Linux kernel style. This isn't because we think it's the best but because it is a well-known standard that we could use without having to define our own.

**Comment by novakpetrovic** [comment]
Thank you very much, it's all clear now.
Cheers
