### ISSUE TITLE
A little change for Clock in C track

### ISSUE THREAD

**Issue by fjarboleda** [exercism/c#374]
Hello:
A few time ago I finnish the C Clock exercisce and I wonder ...
Why the exercisce does no define a struct for hour and minute and a primitive for print it?
If clock dosn't create the structure, why do no call it clock_reset( ) or clock_init( )?
Thank you for your time!

**Comment by ryanplusplus** [comment]
Hi @fjarboleda, that's a good approach and I'd welcome a change to the exercise that made it more object oriented. Would you be interested in creating a pull request that introduces these changes to the exercise?

**Comment by fjarboleda** [comment]
Yes of course, but it my very first time in GitHub, I'll try to do my best...

**Comment by wolf99** [comment]
closed by #393
