### ISSUE TITLE
palindrome-products: Should the check_factors test function be order-insensitive?

### ISSUE THREAD

**Issue by ZapAnton** [exercism/c#375]
I am having a problem with the `test_largest_palindrome_from_single_digit_factors` test case, where the expected factors are initialized as `{{3, 3, NULL},  {1, 9, NULL} }` and are checked by the `check_factors` function in this specific order, while my solution returns factors in the `{ {1, 9, NULL}, {3, 3, NULL} }` order.

Perhaps the `check_factors` could be updated to accept factors in any order?

**Comment by patricksjackson** [comment]
You are correct, it should be updated to allow specifying the factors in any order. Would you like to make the fix?
