### ISSUE TITLE
make doesn't work

### ISSUE THREAD

**Issue by dawids21** [exercism/c#383]
Hello, I have installed GNU Make and I have MinGW compiler but when I type "make test" I receive a messege "make (e=2): The system cannot find the file specified." I don't know how to fix this.

**Comment by ryanplusplus** [comment]
@dawids21 where are you typing `make test`? Are you doing it in the MinGW shell? It's been a long time since I've used MinGW but I think you need to use a MinGW-provided shell, not `cmd.exe`.

**Comment by dawids21** [comment]
Ok i figured it out. I've just installed the ubuntu subsystem on windows and I'm doing that by Linux.
