### ISSUE TITLE
Track progress not updating

### ISSUE THREAD

**Issue by tuyenhn** [exercism/c#391]
Hi, I'm very new to Exercism and don't know how things work. I followed the interactive CLI installation walkthrough and installed Exercism. I use VSCodium as my personal IDE with MinGW64.

I tested the first "hello world" exercise and submitted it but when I went to the solution page (https://exercism.io/my/solutions/8566acf4c5544394bd910cf2bcf1a8f0), it said "Oh dear, we can't find that page. Sorry about that." and the hello world exercise is still incomplete.

I just need to "exercism submit ..." in the cmd right? or are there any extra steps?

**Comment by spiraldancing** [comment]
Hi tuyenhn ... I'm just another guy trying exercism ... but that link you provided is designed to only work for you, when you are logged in.

When you do "exercism submit ...", you should get a clear message, saying "your solution has been submitted successfully", and including a weblink pointing to your online solution in your language track

I assume that's where you got the link you included in your issue.  Make sure you are logged in when you visit that link.  If that doesn't solve the issue, you can try resubmitting the exact same solution a 2nd time, see if that clears it up.

Beyond that, if you're still stuck, you'll have to wait for feedback from someone more familiar w/exercism.

**Comment by tuyenhn** [comment]
Yeah, that link was provided to me after I submitted through the CLI and I'm pretty sure I'm logged in when I enter the link. I submitted for like 5 times already too.

**Comment by ryanplusplus** [comment]
I'll echo what @spiraldancing mentioned and recommend that you be sure you're logged in. If you are logged in, make sure that the API key you're using on the CLI matches the API key for your Exercism user in case you are logged in but to a different account.

**Comment by tuyenhn** [comment]
I reconfigured the CLI with the same CLI token as in the website to make sure. I submitted the .c and .h files and it said: 
"    Your solution has been submitted successfully.
    You can complete the exercise and unlock the next core exercise at:

        Your solution has been submitted successfully.
    You can complete the exercise and unlock the next core exercise at:

    https://exercism.io/my/solutions/8566acf4c5544394bd910cf2bcf1a8f0"

And when I open that webpage there's no indication that I'm signed in but I presumed that since I was logged in automatically, I think the webpage will pick up that account as my credentials.

Sidenote, I HAD an Exercism account set up before but I deleted it, any problems that might cause? And the metadata.json has the same webpage to the solutions like the CLI too.

**Comment by wolf99** [comment]
If you're sure your token and URL are correct, then this is definitely odd behaviour.
Odd because if logged in then obviously you should see the exercise, if not logged in you should be directed to the login page. If the first two conditions are met then at no point should you see the "Oh dear" page.

If you're certain the token and URL are correct (and are transposing correctly between your CLI and the browser both directions), then this is not a track issue but rather an Exercism issue. As such, you should open an issue at https://github.com/exercism/exercism/issues (you can link this issue on that issue so we can track the outcome)
