### ISSUE TITLE
Hello World test fails with apparently-correct solution

### ISSUE THREAD

**Issue by spiraldancing** [exercism/c#392]
I'm sorry, this hardly seems like the right place to gripe about being unable to get my Hello World unit test to pass ... but I'm not seeing anyplace else in exercism to do so (didn't there used to be a discussion area?).

I added the line "printf("Hello, World!");" to the function "const char *hello(void)" in "hello_world.c" ... but "make test" still fails with the message "control reaches end of non-void function" error message.  I also added an #include <stdio.h> to the header, since it doesn't seem to be declared anywhere else, and the unit test complained about it.

I am an experienced programmer.  I'm not even completely new to C (although I am very rusty).  As I understand it, my "printf()" line should be a correct solution.  I only halfway understand the rest of the exercise's content (the various test and vendor/unity stuff, etc) ... but honestly, I shouldn't have to.  I can see in the GitHub history that y'all have already simplified the C "Hello, World" exercise at least once or twice ... I hate to think what it was like originally.

My complete solution looks like this ...

`
#include "hello_world.h"
#include <stdio.h>

const char *hello(void)
{
  printf("Hello, World!");
}
`

What am I missing here?  Thanks.

**Comment by spiraldancing** [comment]
Addendum ... I submitted my incomplete solution ... and then I got to see successful solutions from the community.  So, yes, I've figured out my specific issue.

But the underlying issue remains ... I'm an experienced developer (15+ years of C#/T-SQL/ASP.NET) who was unable to figure out the introductory "Hello World" exercise here ... gods help the noobies.

I love the idea of exercism -- I keep coming back to it, year after year ... but also, year after year, every time I dive into a new language track, I am re-reminded that the setup, tdd framework, instructions and support are (still) too dense, complicated and error-riddled, to use as a primary study tool.

**Comment by patricksjackson** [comment]
There is a Slack actually, and I know students show up there, but I don't think it's advertised much (?) - https://exercism-team.slack.com

Your original issue was (as you've figured out) that the function returns a `const char*`, and the function had no `return` statement. The function definitions are very similar to the C# you're familiar with. It can be confusing, we used to not provide any example at all IIRC.

There are some issues with complexity in some of the tracks, especially in this track. Good news though, we can try to fix it if people tell us where the rough edges are, so thanks for reporting :). The maintainers are often people who learned C a long time ago and have difficulty understanding what it's like for a new learner, so what may seem like obvious issues to you are not always obvious to us. It's also kind of assumed that you are going through a language tutorial or something.

Would something like https://github.com/exercism/cpp/pull/279 have helped? I setup a skeleton solution that the student would receive and heavily annotated that and the test function to try to explain what everything is. (`hello_world.cpp/.h` are provided to the students along with the test file)

C++ is not C, but we could do something similar here.

**Comment by wolf99** [comment]
I like your suggestion @patricksjackson. If it were me I probably wouldn't go _quite_ so in depth on the explanatory comments though as Exercism does expect some level of language knowledge.

For example 

    // This is called an include guard, which ensures that the header is only
    // included once. You could alternatively use '#pragma once'. See
    // https://en.wikipedia.org/wiki/Include_guard

I would instead have put

    // This is called an include guard, which ensures that the header is only
    // See https://en.wikipedia.org/wiki/Include_guard

This covers the area of ensuring that the hello world informs the student how to use the track and how exercises are expected to be completed, but still puts at least some level of self-led learning on the student, rather than... well... spoon-feeding.

**Comment by spiraldancing** [comment]
More complete explanatory comments would help, yes.  I did not understand many of the specific elements in the C "Hello World" exercise.  I should have gone off and learned the meaning of each, on my own initative - and that's on me - but brief comments, either explaining elements, or pointing out which ones the student should learn/understand ...

Also helpful would be some way to more clearly separate the C elements the student is intended to learn, from the testing framework elements, which we should understand eventually, but not hand-in-hand with 'Hello World'.

The main thing I noticed, though, is the introductory directions are not well written, even wrong in 1-2 places ... there's an outstanding 3-month old issue ([exercism/exercism#4805](https://github.com/exercism/exercism/issues/4805) unfortunately filed in the general 'exercism' project, so apparently overlooked?) about the introductory direction to first read the 'Guide' (which no longer seems to exist?)

**Comment by patricksjackson** [comment]
@wolf99 Thanks for the feedback. I did perhaps err on the side of too much hand-holding 👍 

@spiraldancing Yea the docs can (always) use updating... Thanks for the pointer to that issue, the issues in that central repo are supposed to be triaged but it doesn't always happen.

**Comment by wolf99** [comment]
As an indicator of options on this we could also take inspiration from the tutorial for `hello-world` in the Java track: https://github.com/exercism/java/blob/master/exercises/hello-world/TUTORIAL.md that is part of the exercise
