### ISSUE TITLE
Missing Guides

### ISSUE THREAD

**Issue by patricksjackson** [exercism/c#396]
Pulling this from https://github.com/exercism/exercism/issues/4805

> From Tracks / C Track / Hello World / Instructions.
>> Getting Started
>> Make sure you have read the "Guides" section of the C track on the Exercism site. This covers the basic information on setting up the development environment expected by the exercises.

> I do not see anything labelled "Guides". Should there be documentation on using tests, etc?
> I am in independent mode, was this content made available only to users in mentored mode?

It looks like the `Getting Started` description that's in every README needs to be updated to describe the new website? It used to be stored here but I think it's moved somewhere. https://github.com/exercism/c/blob/28c5d0411f18ba4ee0bec82718beaf6b566fc670/config/exercise_readme.go.tmpl

**Comment by wolf99** [comment]
I don't recall there ever being a "Guides" is this specific to the new site or to the C track? I notice that, for example, the Java track does not mention this in the readme template 
(as an aside, the Java track does have a full tutorial linked in the readme for the hello-world exercise https://github.com/exercism/java/blob/master/exercises/hello-world/TUTORIAL.md)

**Comment by patricksjackson** [comment]
I don't recall that either, it was at least before exercism v2 from last year. I don't think it was specific to C, just some old way that the website was organized.

**Comment by wolf99** [comment]
So then do we remove the broken guides link to close this issue, and then follow up on #392 to resolve the issue of lack of guidance?

**Comment by wolf99** [comment]
Turns out the link is correct, there is a guides section on the side bar of the linked page:

![image](https://user-images.githubusercontent.com/281700/79067018-4150e700-7cb4-11ea-9129-8cc96e06cb1d.png)
