### ISSUE TITLE
Intellij open source licenses

### ISSUE THREAD

**Issue by wolf99** [exercism/c#412]
Intellij grant to core contributors on an OSS project.
https://www.jetbrains.com/community/opensource/

Have applied for Intellij open source licenses for this track. 
Have applied for 4 licenses based on the number of maintainers listed in the `config/maintainers.json` file.

1. Any further (or less) contributors that should have licenses?
2. How to distribute licenses? (I have no issue emailing, but some may not want to provide personal email addresses and would not recommend providing them via GitHub issue anyway)
3. Barret seems to have disappeared from GitHub - anyone have any info on a profile name change, or has he left? (if the latter I can update the maintainers file)

**Comment by patricksjackson** [comment]
Well, I had no idea that program existed. I use Clion occasionally at work but I don't have a personal license so this would be great. Thanks for looking into it :)

Assuming you're getting a list of license codes emailing is definitely better than posting them to a Github issue. You can just pull emails from commits, but I have the same username here as my gmail address.

@wolf99 You applied for this specific track right? @KevinWMatthews has been working with me on C++, so I'm guessing we might need to apply separately?

**Comment by ryanplusplus** [comment]
@wolf99 I think that you, me, and @patricksjackson are the only active maintainers. You can pull my email address from commits or, like @patricksjackson, I have the same username as my gmail account.

Thanks for taking the initiative here. I didn't know this program existed.

**Comment by ryanplusplus** [comment]
I actually work with Barrett. He is still alive and well and committing to GitHub. The reason you can't find him is that there's issue in the list of maintainers; his name has two "t"s at the end but it is entered with only one.

**Comment by ryanplusplus** [comment]
I just updated the maintainers list to correct @RealBarrettBrown's username.

**Comment by KevinWMatthews** [comment]
Oh, interesting. I actually bought a personal Intellij license before I started contributing to exercism, but I think it would be cool to have as a resource for exercism developers. I wonder if there is some way that we could apply for the exercism organization as a whole and add new developers as they onboard?

**Comment by wolf99** [comment]
I will forward on if and when they arrive then.

@patricksjackson Yep, I did it for the C track only. Other tracks should be able to apply similarly 😃 .

**Comment by wolf99** [comment]
Still cant assign Barrett on this issue for some reason. I assume he'll get a ping from your mention above though @ryanplusplus.

**Comment by patricksjackson** [comment]
Thanks @wolf99!
