### ISSUE TITLE
Memory Allocation on Saddle Points Exercise

### ISSUE THREAD

**Issue by gabriel376** [exercism/c#413]
I just solved Saddle Points exercise on C track and could not resolve it without a memory leak, using valgrind to check. I have checked all solutions published and all have the same memory leak issue.

The structs of this solution are:
```
typedef struct {                                                                
   size_t row, column;                                                          
} saddle_point_t;                                                               
                                                                                
typedef struct {                                                                
   size_t count;                                                                
   saddle_point_t points[];                                                     
} saddle_points_t; 
```

In file [test_saddle_points.c](https://github.com/exercism/c/blob/master/exercises/saddle-points/test/test_saddle_points.c), `free()` is called just for the main struct `saddle_points_t`, but not for the field `points`.

The [example.c](https://github.com/exercism/c/blob/master/exercises/saddle-points/src/example.c) uses `realloc()` and calculates the size of the main struct + points field, so the `free()` works fine and there is no memory leak.
```
realloc(saddle_points,                                                                                                                                                    
            sizeof(saddle_points_t) +       
            sizeof(saddle_point_t) *        
            ++count);
```

However, I think this approach is not very common, and we can see that all students have submit solutions using `calloc()` for the main struct and another `calloc()` for points field. It's part of mentoring program to check if the solution handles memory allocation correctly and we provide a valgrind option on `make`.

I was expecting the test to free fields point too:
```
free(actual->points)
```

Another minor issue is that students should implement function `saddlePoints`, but the naming convention we have been using for C track is snake_case, so it should be `saddle_points`.

**Comment by wolf99** [comment]
Hi @gabriel376 

Good catch!

I added this exercise. On the PR it was mentioned that we are happy we have a solution that uses `realloc()` 😄 . 

However, if students are not finding a path to implementing it this way and are instead using ways that are "incorrect", then short of adding valgrind testing to solutions I don't see a way to resolve this of the top of my head.

**Comment by wolf99** [comment]
Wondering how compilation is working using `calloc()` on a flexible array member of a struct 🤔

**Comment by ryanplusplus** [comment]
@wolf99 I think that we should probably move in the direction of always having the `free` be done inside of the code under test by exposing a `whatever_free`/`whatever_release`/`whatever_destroy` method. This puts fewer restrictions on the implementation.

**Comment by wolf99** [comment]
Good call @ryanplusplus

**Comment by gabriel376** [comment]
Thank you all
