### ISSUE TITLE
First Test Case Makefile Is Wrong

### ISSUE THREAD

**Issue by ShockvaWe** [exercism/c#435]
Hello-world test case is not workin properly.

When you do `make test` it gives an error which is:
`
Compiling tests.out /usr/bin/sh: cc: command not found make: *** [makefile:34: tests.out] Error 127
`
I figured out what the problem is and added cc=gcc and CC=gcc lines to my makefile but It took a lot time to figure it out as a beginner.

**Comment by bergjohan** [comment]
That's odd, `cc` should normally be a symlink to your installed C compiler. What system are you using to compile the exercise?

To avoid editing the `makefile`, you could either run `make CC=gcc`, or `export CC=gcc` before running `make`.

**Comment by ShockvaWe** [comment]
I am using mingw-w64 on Windows 10, all on path.
Thanks for the tip, I just published this issue because there might be other beginners who will face it and get frustrated.

**Comment by ShockvaWe** [comment]
I am using mingw-w64 on Windows 10, all on path.
Thanks for the tip, I just published this issue because there might be other beginners who will face it and get frustrated.

**Comment by bergjohan** [comment]
Yeah okay, there seems to be an issue that the `mingw-w64` `gcc` package doesn't include `cc.exe`.

**Comment by ryanplusplus** [comment]
We could modify the makefiles to add `CC ?= gcc` to default to `gcc` when `CC` is not set.

**Comment by ryanplusplus** [comment]
@ShockvaWe can you confirm that adding `CC ?= gcc` at the beginning of the makefile fixes the issue on your system?

**Comment by bergjohan** [comment]
Yes, that could work. It looks like it's been fixed in mingw though, see https://github.com/msys2/MINGW-packages/pull/1034.

**Comment by ryanplusplus** [comment]
> Yes, that could work. It looks like it's been fixed in mingw though, see [msys2/MINGW-packages#1034](https://github.com/msys2/MINGW-packages/pull/1034).

Even better!

**Comment by ShockvaWe** [comment]
@ryanplusplus Yes adding `CC ?= gcc` at the beginning of the makefile fixes the issue.

**Comment by bergjohan** [comment]
@ShockvaWe What is the version of your mingw-w64-gcc package? Could you take a look in your mingw bin directory, do you see a cc.exe?

**Comment by ShockvaWe** [comment]
I don't know if that's what you are asking:
`MSYS_NT-10.0-18363 DESKTOP-02QKGBS 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys`

No there is no cc.exe

**Comment by bergjohan** [comment]
Thanks, if you search for the gcc package in mingw, what's the name of it, I think the version is included in the name?

Could you also verify that there are no new updates available for the gcc package?

**Comment by l0nax** [comment]
But `CC` (and `CXX` for C++) are _default_ environment values –, especially in the POSIX world.

So I don't really see the need to set `CC` statically in all Makefiles.
This looks more like that the (build) environment isn't correctly installed/ setupped.

**Comment by ryanplusplus** [comment]
This looks like a mingw issue, not something we can fix here.
