### ISSUE TITLE
Make Test Doesn't Run Tests

### ISSUE THREAD

**Issue by JimLynchCodes** [exercism/c#439]
Hi, 

When I download the hello world challenge and run `make test` I just get this output:

```
make: `test' is up to date.
```
![Screen Shot 2020-03-24 at 2 58 52 PM](https://user-images.githubusercontent.com/5354163/77466167-3fe07d00-6de0-11ea-8b09-19a56a1911f1.png)

Anyone know what I am doing wrong here? 🤔

**Comment by patricksjackson** [comment]
It should be running the tests even if you haven't made any changes, so that output is never expected. It's likely there's just something not quite right with your setup.

What platform are you trying to run this on?
Also the output of these commands run from the directory you're using would be helpful to rule some things out:

```
make test
make --version
cc --version
ls -R
```

And the contents of your makefile, `cat makefile` (you may have an old version if you started exercism a while ago, as the site will pin the version when you start the exercise)

**Comment by JimLynchCodes** [comment]
Thanks @patricksjackson !

I'm running it on macOS v10.15.3

`make --version`
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

`cc --version`
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

`ls -R`
README.md      src            tests.out
makefile       test           tests.out.dSYM

./src:
hello_world.c hello_world.h

./test:
test_hello_world.c vendor

./test/vendor:
unity.c           unity.h           unity_internals.h

./tests.out.dSYM:
Contents

./tests.out.dSYM/Contents:
Info.plist Resources

./tests.out.dSYM/Contents/Resources:
DWARF

./tests.out.dSYM/Contents/Resources/DWARF:
tests.out

`cat makefile`
### If you wish to use extra libraries (math.h for instance),
### add their flags here (-lm in our case) in the "LIBS" variable.

LIBS = -lm

###
CFLAGS  = -std=c99
CFLAGS += -g
CFLAGS += -Wall
CFLAGS += -Wextra
CFLAGS += -pedantic
CFLAGS += -Werror
CFLAGS += -Wmissing-declarations
CFLAGS += -DUNITY_SUPPORT_64

ASANFLAGS  = -fsanitize=address
ASANFLAGS += -fno-common
ASANFLAGS += -fno-omit-frame-pointer

test: tests.out
	@./tests.out

memcheck: test/*.c src/*.c src/*.h
	@echo Compiling $@
	@$(CC) $(ASANFLAGS) $(CFLAGS) src/*.c test/vendor/unity.c test/*.c -o memcheck.out $(LIBS)
	@./memcheck.out
	@echo "Memory check passed"

clean:
	rm -rf *.o *.out *.out.dSYM

tests.out: test/*.c src/*.c src/*.h
	@echo Compiling $@
	@$(CC) $(CFLAGS) src/*.c test/vendor/unity.c test/*.c -o tests.out $(LIBS)

**Comment by wolf99** [comment]
Just to rule out issue with the target name vs directory name, can you try the following?
```
make clean
make
```
(Note no target argument for the second make command)

**Comment by JimLynchCodes** [comment]
Thanks @wolf99!

This worked for me!

It would be great if this was in the README of the projects and the "Running the Tests" page on Exercism! 😉

**Comment by ryanplusplus** [comment]
#441 should resolve the issue that caused this
