### ISSUE TITLE
Clang not warning about unused static variable

### ISSUE THREAD

**Issue by elyashiv** [exercism/c#456]
I had a student that declared a static array in the header file. This won't compile with gcc - the tests won't compile because there is an unused static variable.

Clang compiles it (student using clang-11 on mac, tested with clang-10 on ubuntu)

I guess there is a flag to add so clang warns about that, but couldn't find one.

**Comment by ryanplusplus** [comment]
This doesn't pick it up?
https://clang.llvm.org/docs/DiagnosticsReference.html#wunused-variable

**Comment by elyashiv** [comment]
Seems like it doesn't :(

**Comment by wolf99** [comment]
@elyashiv are you able to post a link to the code?
It would be interesting to see the exact case that this occurs in.

**Comment by elyashiv** [comment]
@wolf99 [this gist shows it](https://gist.github.com/elyashiv/7ab681a166bc3b6e16496c42fbba7e2f).

```
❰elyashiv❙/tmp/tmp.xBWknbGP8R❱✔≻ gcc -Wall *.c
In file included from main.c:2:
test.h:5:12: warning: ‘a’ defined but not used [-Wunused-variable]
    5 | static int a = 1;
      |            ^
❰elyashiv❙/tmp/tmp.xBWknbGP8R❱✔≻ clang -Wall -Wunused-variable *.c
❰elyashiv❙/tmp/tmp.xBWknbGP8R❱✔≻ 
```

**Comment by ryanplusplus** [comment]
I think that what's happening is that `clang` is being clever and noticing that while `a` not used, it's defined in a header and thus _could_ be used by another module. If a static is declared and unused in a `.c` file it does warn.

See https://stackoverflow.com/questions/53619461/clang-does-not-warn-for-defined-but-not-used-in-header-gcc-does

**Comment by wolf99** [comment]
My thinking was the same as @ryanplusplus . 

As this appears to be an issue in how Clang handles the build process, and considering the fact that it does not seem to have been fixed in the last 2+ years, I'm not sure if there is anything we can do about it (in standard tooling at least).

**Comment by ryanplusplus** [comment]
Looks like a `clang` issue, not something we're going to be able to solve.
