### ISSUE TITLE
List-ops improvments

### ISSUE THREAD

**Issue by elyashiv** [exercism/c#468]
I think list-ops will look nicer with linked lists. We can move the exercise to after the linked list exercise, and require the student to use their solution with this.

What do you think?

**Comment by ryanplusplus** [comment]
Without seeing it in action, I'm a bit worried that the linked list code might distract from the list ops code.

**Comment by elyashiv** [comment]
Ok. I will try to find some time to make an example.

**Comment by wolf99** [comment]
> Without seeing it in action, I'm a bit worried that the linked list code might distract from the list ops code.

I believe this is why we didn't go down that route first time around.
Interested to see if another implementation could do keep the functionality clear though!
