### ISSUE TITLE
Rail fence cipher still locked

### ISSUE THREAD

**Issue by dawids21** [exercism/c#470]
Hello. I have almost all exercises for C track completed except for Rail Fence Cipher which is still locked.

**Comment by ryanplusplus** [comment]
This should be unlocked [by the isogram exercise](https://github.com/exercism/c/blob/master/config.json#L877). Have you completed isogram?

**Comment by dawids21** [comment]
Yes, I have completed the isogram exercise

![2020-08-01_16-39-59_screenshot](https://user-images.githubusercontent.com/50179033/89103905-b0924880-d415-11ea-882b-6151b233ad3b.png)

**Comment by dawids21** [comment]
Yes, I have completed the Isogram exercise\

![2020-08-01_16-40-57_screenshot](https://user-images.githubusercontent.com/50179033/89103929-da4b6f80-d415-11ea-89c0-baefd032f145.png)

**Comment by ryanplusplus** [comment]
@iHiD is this something we've seen before?

**Comment by dawids21** [comment]
When I went to the Isogram page, I saw that I could have updated it but still I have that exercise locked.

**Comment by wolf99** [comment]
Are you completing in un-mentored mode?

https://github.com/exercism/exercism/issues/4881

**Comment by dawids21** [comment]
No. I've completed all core exercises in mentored mode.

**Comment by iHiD** [comment]
I've run my magic script which goes through everything to check it's correct. This should fix it in the next few hours @dawids21 (it takes a while to run). Please let me know whether it fixes it or not.

**Comment by dawids21** [comment]
Yes, now it's fixed. Thank you for your help.
