### ISSUE TITLE
[v3] Concepts List

### ISSUE THREAD

**Issue by bergjohan** [exercism/c#601]
# C

I started a list of concepts based on [https://github.com/exercism/v3/tree/master/reference](https://github.com/exercism/v3/tree/master/reference), and using the references at the bottom.

## Specialties (concepts)
 - [Incomplete Types](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Incomplete-Types)
 - [Volatile](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Type-Qualifiers)
 - [Storage Class Specifiers](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Storage-Class-Specifiers)
 - [Renaming Types](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Renaming-Types)
 - [Bit Fields](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Bit-Fields)
 - [Labels](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Labels)
 - [The switch Statement](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#The-switch-Statement)
 - [Blocks](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Blocks)
 - [The Null Statement](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#The-Null-Statement)
 - [The goto Statement](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#The-goto-Statement)
 - [The typedef Statement](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#The-typedef-Statement)
 - [Variable Length Parameter Lists](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Variable-Length-Parameter-Lists)
 - [Calling Functions Through Function Pointers](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Calling-Functions-Through-Function-Pointers)
 - [Static Functions](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Static-Functions)
 - [Program Structure](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Program-Structure)
 - [Scope](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Scope)
 - [Dynamic memory management](https://en.cppreference.com/w/c/memory)
 - [Date and time utilities](https://en.cppreference.com/w/c/chrono)
 - [Strings library](https://en.cppreference.com/w/c/string)
 - [Algorithms](https://en.cppreference.com/w/c/algorithm)
 - [File input/output](https://en.cppreference.com/w/c/io)

## Specialties (types)
 - [Complex Number Types](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Complex-Number-Types)
 - [Enumerations](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Enumerations)
 - [Unions](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Unions)

## Concepts
 - [Arithmetic](https://github.com/exercism/v3/blob/master/reference/concepts/arithmetic.md)
 - [ASCII](https://github.com/exercism/v3/blob/master/reference/concepts/ascii.md)
 - [Assignment](https://github.com/exercism/v3/blob/master/reference/concepts/assignment.md)
 - [Bitwise manipulation](https://github.com/exercism/v3/blob/master/reference/concepts/bitwise_manipulation.md)
 - [Boolean logic](https://github.com/exercism/v3/blob/master/reference/concepts/boolean_logic.md)
 - [Comments](https://github.com/exercism/v3/blob/master/reference/concepts/comments.md)
 - [Comparisons](https://github.com/exercism/v3/blob/master/reference/concepts/comparisons.md)
 - [Conditionals](https://github.com/exercism/v3/blob/master/reference/concepts/conditionals.md)
 - [Constants](https://github.com/exercism/v3/blob/master/reference/concepts/constants.md)
 - [Expressions](https://github.com/exercism/v3/blob/master/reference/concepts/expressions.md)
 - [Functions](https://github.com/exercism/v3/blob/master/reference/concepts/functions.md)
 - [Loops](https://github.com/exercism/v3/blob/master/reference/concepts/loops.md)
 - [Macros](https://github.com/exercism/v3/blob/master/reference/concepts/macros.md)
 - [Operators](https://github.com/exercism/v3/blob/master/reference/concepts/operators.md)
 - [Recursion](https://github.com/exercism/v3/blob/master/reference/concepts/recursion.md)
 - [Return value(s)](https://github.com/exercism/v3/blob/master/reference/concepts/return_values.md)
 - [Signedness](https://github.com/exercism/v3/blob/master/reference/concepts/signedness.md)
 - [Type casting (type conversion, type coercion)](https://github.com/exercism/v3/blob/master/reference/concepts/type_casting.md)
 - [Variable Shadowing](https://github.com/exercism/v3/blob/master/reference/concepts/variable_shadowing.md)
 - [Variables](https://github.com/exercism/v3/blob/master/reference/concepts/variables.md)

## Types
 - [Array](https://github.com/exercism/v3/blob/master/reference/types/array.md)
 - [Bit](https://github.com/exercism/v3/blob/master/reference/types/bit.md)
 - [Boolean](https://github.com/exercism/v3/blob/master/reference/types/boolean.md)
 - [Byte](https://github.com/exercism/v3/blob/master/reference/types/byte.md)
 - [Bytes](https://github.com/exercism/v3/blob/master/reference/types/bytes.md)
 - [Char](https://github.com/exercism/v3/blob/master/reference/types/char.md)
 - [Double](https://github.com/exercism/v3/blob/master/reference/types/double.md)
 - [Floating-point number](https://github.com/exercism/v3/blob/master/reference/types/floating_point_number.md)
 - [Integer](https://github.com/exercism/v3/blob/master/reference/types/integer.md)
 - [Long](https://github.com/exercism/v3/blob/master/reference/types/long.md)
 - [Null](https://github.com/exercism/v3/blob/master/reference/types/null.md)
 - [Pointer](https://github.com/exercism/v3/blob/master/reference/types/pointer.md)
 - [Short](https://github.com/exercism/v3/blob/master/reference/types/short.md)
 - [Signed number representation](https://github.com/exercism/v3/blob/master/reference/types/signed.md)
 - [String](https://github.com/exercism/v3/blob/master/reference/types/string.md)
 - [Struct](https://github.com/exercism/v3/blob/master/reference/types/struct.md)
 - [Unsigned number representation](https://github.com/exercism/v3/blob/master/reference/types/unsigned.md)

## Resources used
 - [The GNU C Reference Manual](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html)
 - [cppreference](https://en.cppreference.com/w/)

**Comment by wolf99** [comment]
This listing is captured in https://github.com/exercism/c/tree/main/reference
