### ISSUE TITLE
CI: split tests from checks and add clang build

### ISSUE THREAD

**Issue by wolf99** [exercism/c#629]
It would be good to have the exercise tests built on their own job, separate job to the "checks" (`verify-indent`, `check-unitybegin`, `verify -unity-version`, `shellcheck`).

It would also be good, once the above is in place, to build the tests with Clang (also on its own job) as well as with GCC, as used to happen when Travis CI was used.
It seems the Ubuntu 18.04 GH job runner virtual environment that we use has both Clang and GCC available (https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) and actually I'm not too sure which is being used currently - I assumed `$CC` picked up GCC automagically but am not really sure!

Thoughts?

**Comment by ryanplusplus** [comment]
:+1:

**Comment by ryanplusplus** [comment]
After merge this is failing (though it succeeded in the PR...). I have to get to work soon so I haven't had a chance to investigate.

**Comment by wolf99** [comment]
I think it may be failing because I neglected to change the `name:` property when I created the new file by duplicating the original `build.yaml`, meaning that the CI would see to workflows with the same name, which is probably confusing for it!
