### ISSUE TITLE
grade-school: student name pointer assignment

### ISSUE THREAD

**Issue by sylenth1cs50** [exercism/c#660]
Hello!

Thank you for the brilliant work you are doing!

---

After finishing this exercise and reading some of the community solutions, I saw that some of the solutions passed even though, in my opinion, they are technically not correct.

Student structure:
```
#define MAX_NAME_LENGTH 20

typedef struct {
   uint8_t grade;
   char *name;
} student_t;
```
The prototype of `add_student()`:

```
bool		add_student(const char* name ,uint8_t grade);
```
`name` from `student_t` struct is a pointer, and assigning the pointer to the `name` parameter passed to the function pass the tests.

Let's say we have a roster variable:

```
static roster_t roster;
```

If in the `add_student()` function we do:

```
roster.students[i].name = name;
```

Both pointers will point to the same address. The tests will pass because the parameter is the `expected->students[i].name`.

---

Thank you for your time!

**Comment by ryanplusplus** [comment]
Hey @sylenth1cs50, I see what you're saying. Do you have a proposed solution? One option might be to copy the name to a stack allocated array then overwrite the contents after the call to `add_student` so that it's not possible to just store the pointer.

**Comment by sylenth1cs50** [comment]
Hey @ryanplusplus.

I think what you propose, copying the name to a buffer and overwriting the content after the call to `add_student`, is an excellent solution.


Some things to consider, in my opinion, would be stack versus heap memory allocation, which are both valid.


For consistency, in the case of stack allocation, one addition is to also change the `name` from the `student_t` struct  to an array of characters:

```
char	name[MAX_NAME_LENGTH + 1];
```


In the case of heap allocation, I think `MAX_NAME_LENGTH` becomes irrelevant.

**Comment by ryanplusplus** [comment]
@sylenth1cs50 here's a quick pass at a fix:
https://github.com/exercism/c/pull/661
