### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/c#680]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total..........262
✅ Successful.....261
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........1

Errors in ./docs/INSTALLATION.md
<span style="color:#ff5555">✗ https://msdn.microsoft.com/en-us/commandline/wsl/about (HTTP status client error (403 Forbidden) for url (https://msdn.microsoft.com/en-us/commandline/wsl/about))</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by wolf99** [comment]
Hi @ErikSchierboom ,

What are you using to check links? 
We could add this into the CI, or perhaps it could be incorporated into the configlet utility?

**Comment by ErikSchierboom** [comment]
@wolf99 https://github.com/lycheeverse/lychee I'm thinking of making it a GitHub Action.
