### ISSUE TITLE
Move from GNU indent to ...?

### ISSUE THREAD

**Issue by wolf99** [exercism/c#716]
On Ubuntu 20.04 the version of GNU Indent available is 2.2.12.

This has [a bug](https://savannah.gnu.org/bugs/?54673) that causes the `--space-after-if`/`-sai` to consistently misbehave, meaning that Indent can never be satisfied. This argument is used in our use case as part of the `-linux` shortcut argument that we currently specify.

If we are to update to using Ubuntu 20.04 (see #713, #717 ), then we will need to overcome this issue.

As the [last release](https://git.savannah.gnu.org/cgit/indent.git) of Indent was 3 years ago (2019), after the bug was filed (2018), and the release before that 12 years ago, I don't see Indent being updated to resolve this issue any time soon. Therefore I see several bad options and one other option:

- Split the Indent task to its own workflow and continue using Ubuntu 18.04 there (not great to continue requiring old versions, especially for local development)
- Change our arguments to indent (not great as a space after an if statement is quite a widespread usage
- Try to change exercises so that this bug is never encountered (not great as function pointers are a useful part of the language and should be part of at least one exercise)
- Change from using indent to using something else (e.g. astyle)

Thoughts?

---

Information on the GNU Indent bug and how it affects this track:

In the list-ops practice exercise `example.c`, the `filter_list()` function checks that a function pointer argument is not `NULL`.
1. On a pass of Indent it seems like Indent determines that the `if` that checks the function pointer variable is actually a  function named `if()` and so moves the opening bracket to be the next character directly after the `if`.
2. On a subsequent pass of Indent it decides differently that actually it is an `if` statement and so adds the space back in before the opening bracket.
3. GOTO 1;

To reproduce in a minimum verifiable example, create a `test.c` file

```c
void foo(void (*bar)(void))
{
   if (!bar)
      return;
}
```

Then in a bash terminal run

```console
$ indent -linux -i3 -nut ./test.c  # First pass
$ diff ./test.c ./test.c~  # Shows indent has removed space after if
4c4
<    if (!bar)
---
>    if(!bar)
$ indent -linux -i3 -nut ./test.c  # Second pass
$ diff ./test.c ./test.c~  # Shows indent has added space after if
4c4
<    if(!bar)
---
>    if (!bar)

# This continues eternally
```

**Comment by ryanplusplus** [comment]
I don't love the current style so I'm not opposed to switching formatters or the style. I've never used `astyle`, but I'm fond of `clang-format`. What's nice about `clang-format` is that it can read the configuration from a file (`.clang-format`) so that editors and the command line can use the same configuration.

**Comment by wolf99** [comment]
Astype was simply the first one I found in web search 😂.
I'll read up on clang-format and have a go at adding it.
