### ISSUE TITLE
Why is -DUNITY_OUTPUT_COLOR not the default?

### ISSUE THREAD

**Issue by joshgoebel** [exercism/c#742]
OMG I just went looking if color could be added and saw it was an option, just one we're not turning on by default.  Could we?

**Comment by wolf99** [comment]
Wasn't aware of this option. Sounds like a good idea. Only concern I would have is how well it works cross platform, especially on Windows as garbled output that ANSI codes could produce there would be worse than no color.

Can you test that, maybe with mingw and visual studio if you have them available (let us know if not)?

**Comment by joshgoebel** [comment]
Sorry, no Windows here. 🤷🏻‍♂️  The other tracks have test runners that use ANSI - though perhaps it's dependent upon platform?

**Comment by joshgoebel** [comment]
It's just an ifdef... We could probably just make it conditional based on some #ifdef that is set for platform, no?

```c
#ifdef UNITY_OUTPUT_COLOR
const char PROGMEM UnityStrOk[]                            = "\033[42mOK\033[00m";
const char PROGMEM UnityStrPass[]                          = "\033[42mPASS\033[00m";
const char PROGMEM UnityStrFail[]                          = "\033[41mFAIL\033[00m";
const char PROGMEM UnityStrIgnore[]                        = "\033[43mIGNORE\033[00m";
#else
const char PROGMEM UnityStrOk[]                            = "OK";
const char PROGMEM UnityStrPass[]                          = "PASS";
const char PROGMEM UnityStrFail[]                          = "FAIL";
const char PROGMEM UnityStrIgnore[]                        = "IGNORE";
#endif
```

**Comment by ryanplusplus** [comment]
According to Wikipedia, Windows has supported ANSI escape codes since Windows 10 version 1511 in 2016 so I think we could safely enable it. I'm sure there are a few Windows 7 holdouts, but even Microsoft cut them off ~2 years ago.

**Comment by wolf99** [comment]
Sounds good then! 

I guess it will need setting in the makefile of each exercise.

**Comment by joshgoebel** [comment]
Yes, I assume they are identical. We should have some sort of script to update them all but I didn't see a script like that already when I went looking for one.

**Comment by wolf99** [comment]
Not quite all identical as you've seen by the PR. But a script is a good idea, could you open an issue for that?
