### ISSUE TITLE
Isogram passed all online, fails 2 locally

### ISSUE THREAD

**Issue by bobahop** [exercism/c#760]
The code below passed all tests online but failed two tests involving hyphens when run locally

```c
#include "isogram.h"
#include <string.h>
#include <ctype.h>
#include <stdio.h>

bool is_isogram(const char phrase[]) {
    
    if(!phrase) {
        return 0;
    }

    char copyPhrase[strlen(phrase)];

    for (int i = 0; i < (int)strlen(phrase); i++) {
        copyPhrase[i] = tolower(phrase[i]);
        if (!isalpha(copyPhrase[i])) {
            continue;
        }
        for (int j = 0; j < (int)strlen(phrase); j++) {
            if (i != j && copyPhrase[i] == copyPhrase[j]) {
                return 0;
            }
        }
    }
    return 1;
}





#ifndef ISOGRAM_H
#define ISOGRAM_H

#include <stdbool.h>

bool is_isogram(const char phrase[]);

#endif
```

```
test/test_isogram.c:101:test_empty_string:PASS
test/test_isogram.c:102:test_null:PASS
test/test_isogram.c:103:test_isogram_with_only_lower_case_characters:PASS
test/test_isogram.c:104:test_word_with_one_duplicated_character:PASS
test/test_isogram.c:105:test_word_with_one_duplicated_character_from_end_of_alphabet:PASS
test/test_isogram.c:106:test_longest_reported_english_isogram:PASS
test/test_isogram.c:107:test_word_with_duplicated_letter_in_mixed_case:PASS
test/test_isogram.c:108:test_word_with_duplicated_letter_in_mixed_case_lowercase_first:PASS
test/test_isogram.c:63:test_hypothetical_isogrammic_word_with_hyphen:FAIL: Expected TRUE Was FALSE
test/test_isogram.c:110:test_hypothetical_word_with_duplicated_character_following_hyphen:PASS
test/test_isogram.c:76:test_isogram_with_duplicated_hyphen:FAIL: Expected TRUE Was FALSE
test/test_isogram.c:112:test_made_up_name_that_is_an_isogram:PASS
test/test_isogram.c:113:test_duplicated_character_in_the_middle:PASS
test/test_isogram.c:114:test_same_first_and_last_characters:PASS

-----------------------
14 Tests 2 Failures 0 Ignored
FAIL
```

**Comment by bobahop** [comment]
BTW, for VLAs, they were introduced in C99 but were made optional in C11, so compilers aren't required to support them. For instance, my Microsoft compiler flags them as an error, while my gnu compiler supports them. I advise against them when mentoring.

**Comment by siebenschlaefer** [comment]
@bobahop My point is, this solution invokes UB, it might behave differently on different platforms, it might behave differently on multiple executions on the same machine, it might seemingly work and then do something unexpected on the day of an important presentation. With undefined behavior anything can happen (e.g. the often quoted "nasal demons" or "pregnant cats"). And I don't think we can do much against that.

**Comment by ryanplusplus** [comment]
> @bobahop My point is, this solution invokes UB, it might behave differently on different platforms, it might behave differently on multiple executions on the same machine, it might seemingly work and then do something unexpected on the day of an important presentation. With undefined behavior anything can happen (e.g. the often quoted "nasal demons" or "pregnant cats"). And I don't think we can do much against that.

:100:

This can and does differ from compiler to compiler and OS to OS so unless we test every combination in the online editor (not even remotely plausible), we'll have to rely upon mentors to address this.
