### ISSUE TITLE
makefiles too strict? too many warnings as errors distract from the exercise

### ISSUE THREAD

**Issue by BlameTroi** [exercism/c#796]
I've been wrestling with this over a couple of exercises. Using current GCC/LD/GLIBC on manjaro, figuring out feature test macros and fighting false positive warnings slow down the actual work of solving the problems.

One example. Having to wrap a strncpy() in #pragmas to get around a false stringop-overflow warning.
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstringop-overflow"
				strncpy((words[next]).text, token, MAX_WORD_LENGTH);
#pragma GCC diagnostic pop
```
The text field is defined as a char[MAX_WORD_LENGTH+1] array but the compiler (gcc 12) says the move is to a 0 byte field.

Another example is both reallocarray() and strdup() requiring a feature test macro to be exposed by headers. Defining _DEFAULT_SOURCE in the makefile fixed this.

Should students be updating the makefiles and submitting them with their solutions? Should they be expected to deal with esoterica around paranoid warnings?

I guess this is philosophical. I can get around all of these problems by rolling my own functions for everything. That's my personal preference, but I think in professional settings we want to teach people to use the standard libraries.

If the makefile is going to specify warnings as errors and being pendantic, it should better expose feature test gated functions.

**Comment by ryanplusplus** [comment]
Hey @BlameTroi,

The reason that we have warnings turned up is that they help to make sure that code is portable and correct. Not every warning issued is going to be valuable, but many of them are going to keep a learner from doing something bad without knowing it. I work in large projects with stricter warnings than are used here and, with modern compilers, I haven't had to do anything funky to do something I should be allowed to do.

I'm only on GCC 11 but the sample solutions all build clean with no change to the makefile and without avoiding the standard library. Can you check to see the the samples for the exercises you're having issues with build cleanly with GCC 12? My first thought regarding the issue you're having with `strncpy` is that GCC 12 may have a problem or there may be a real issue that is being papered over by the `pragma`. I can't say for sure without more context.

The reason for the other issue you mentioned is that you're using functions that aren't standard C. You have to specify `_DEFAULT_SOURCE` to opt into using functions that aren't portable. IMO this is a good thing and is an example of the warnings doing the right thing by making .

You should not need to avoid the standard library if warnings are enabled. Without context it's really difficult for me to say why exactly you're seeing what you're seeing, but I can say that in my experience I've only gotten into fights with the compiler when my code was non-portable or problematic in a way that I didn't yet understand. Modern compilers are _very_ good.

**Comment by wolf99** [comment]
FYI also that the the exercises (incl makefiles) are designed to use the stdlib. The functions strduo() and reallocarray() are not part of the stdlib IIRC, so this may be why the compiler is fighting you on those.

**Comment by BlameTroi** [comment]
Sorry for the late reply. The conceptual problem for me is that the "non-standard" calls have at some times been seen as standard, and they are declared in the standard library includes, albeit with feature test macros. Just reading the man pages, it's easy to assume they should be available.

I can't think of a good way to explain this in the course material. Thanks.
