### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/c#8]
_Note: the launch checklist was woefully outdated, since this got created over two years ago, so I deleted it._

If you are interested in leading the charge on getting this track launched, then comment below, and I'll help get this party started based on whatever is current at the time.

We have a launch guide that we'll keep up to date with changes here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

**Comment by kytrinyx** [comment]
I wrote a launch guide that I hope is an improvement over the launch checklist. It lives here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

If anything is unclear, please ask questions, as that helps me figure out what to write about next or where we need more detail.

**Comment by Phanatos-** [comment]
I'd like to help getting the C track launched, how can I help?

**Comment by ryanplusplus** [comment]
Hey @Phanatos- 

The thing that I think we most need is just to have a consistent level of quality in the exercises. We've scrubbed a lot of them for quality, but if you can spare a bit of time to go through and identify any that are too complicated or sloppy and put up a PR to make things better, that would be much appreciated. If you go through and find that everything is in an acceptable state, I think we can go ahead and flip the switch.

**Comment by Phanatos-** [comment]
Great, I'll take a look around to the current exercises and see what I can help with!

**Comment by ryanplusplus** [comment]
Thanks!

**Comment by Gamecock** [comment]
Ryan, I'm happy to help too, let me know what you need.

**Comment by kytrinyx** [comment]
> I think Anagram should be moved later in the track. A lot of people having trouble with the malloc.

That's a good observation. Sounds like a wise move.

> Is it worth updating the code to have all except the first test commented out, and update the ReadMe to say after one test passes uncomment the next?

This is probably a separate, track-wide discussion. If it's done, it should probably be done for all of the exercises, and then update the README template (`config/readme.go.tmpl`) and then use Configlet to regenerate the exercise READMEs.

**Comment by wolf99** [comment]
Can we 'hacktoberfest this'? From what I can see there is very little left to be done to launch. Maybe add the 'C' topic to the repository, check everything in the README and the docs is still relevant and correct, get 184 closed (nearly done AFAIK)... anything else?

**Comment by ryanplusplus** [comment]
@wolf99 I think you're right -- we have just a few more issues to go. How do you propose "hacktoberfesting" this? Add the label to try to get help or just power through by the end of October?

**Comment by wolf99** [comment]
Both 😄  

I think the docs and code are at least at a level that it is easy enough to start contributing if people want to. Maybe we could add a section to the README to show on the "front page" what are the issues we hope to get done and why, possibly with a link to this issue. 

At the same time it would be cool if we that are already involved took the chance (depending on each person's availability) to power through some of the outstanding items. If we keep the issues update with the ongoing work then it should be easy enough for new people to join in with this even if just to provide suggestions.

**Comment by ryanplusplus** [comment]
Got it. For now I added the "Hacktoberfest" label to the 4 outstanding tickets.

**Comment by wolf99** [comment]
Have added a PR to add relevant info to the README for the duration, #220

**Comment by Gamecock** [comment]
@ryanplusplus the only "Hacktoberfest" label I see is #5, is that all that's left?

**Comment by ryanplusplus** [comment]
@Gamecock I think I simply failed at labeling. Should be all good now (though #184 is closed). Sorry!
