### ISSUE TITLE
[c language] - queen attack invalid test 'test_can_attack_on_first_diagonal'

### ISSUE THREAD

**Issue by armhzjz** [exercism/c#838]
There is an error on the test named 'test_can_attack_on_first_diagonal' of the queen attack challenge of the C language.

This test expects the solution to return the enumeration "CAN_ATTACK" even though the row of the black queen is set to an (invalid) value of 0 (zero).

The but is also found in another test (i.e. test_can_attack_on_fourth_diagonal).

If this is not a bug, I'd love to see then a better explanation/specification of the problem (i.e. explicitly mentioning the valid range of values for both columns and rows in the problem's page).

If this is in deed a bug, it is also not clear whether the expected value of these tests should be "INVALID_POSITION" or if the values of the black queen's rows should be set to values that allow for a "CAN_ATTACK" return value of the function.

**Comment by ryanplusplus** [comment]
Hey @armhzjz, 0 through 7 are valid positions on the board. Negative positions and positions greater than 7 are invalid. If you look at the [`test_white_queen_must_have_row_on_board`](https://github.com/exercism/c/blob/main/exercises/practice/queen-attack/test_queen_attack.c#L25-L37) test, the white queen's row is invalid, not the black queen's row or column.

**Comment by armhzjz** [comment]
Hi @ryanplusplus, I see now. I didn't pay attention in detail to the rest of the tests.
I think I was misled by the diagram on the overview page of the problem - it shows row enumerated 1 to 8 (columns enumerated a to h).
So, I immediately assume 1 to 8 was the valid range.
Thank you!

**Comment by ryanplusplus** [comment]
Sure thing!
