### ISSUE TITLE
Add `make memcheck` tip for the HELP.md file.

### ISSUE THREAD

**Issue by glennj** [exercism/c#921]
I recently finished linked-list, my first exercise with malloc and free, and I was looking for instructions about how to check for leaked memory. I ended up on the track docs testing page which is kind of out of the way.

Are maintainers open to a PR for adding some words about make memcheck to `exercises/shared/.docs/tests.md` (so that it gets included in the `HELP.md` file that is downloaded)?

Perhaps something like
````markdown
To check for memory leaks (allocated memory that is not freed), run:

```console
$ make memcheck
```
````

**Comment by ryanplusplus** [comment]
I think it's a good idea
