### ISSUE TITLE
Rework the gigasecond exercise?

### ISSUE THREAD

**Issue by glennj** [exercism/c#924]
I was highly underwhelmed by the gigasecond exercise, where (spoiler) the solution is adding a constant to the function parameter.

I'd like to do something to make it a bit more challenging, something to force the student to use time.h

Are maintainers open to that?

**Comment by ryanplusplus** [comment]
👍

**Comment by wolf99** [comment]
Hmm I could be wrong but IIRC the intention of the gigasecond exercise is to be relatively simple.
Introducing time.h I'm any significant way may add needless complexity and could imagine different results depending on platform.

However, I would be interested to see if I am wrong on these points!

**Comment by glennj** [comment]
Well, there's "relatively simple" and then there's `int gigasecond(int a) {return a + 1e9}`

I'll play around with it. Maybe it'll turn into `gigasecond2`.
