### ISSUE TITLE
Pascal's Triangle has a bad Test Case defining Zero Rows.  

### ISSUE THREAD

**Issue by elmq0022** [exercism/c#934]
This [test](https://github.com/exercism/c/blob/main/exercises/practice/pascals-triangle/test_pascals_triangle.c#L43-L50) is not consistent with the definition of Pascal's Triangle.    There is no row zero with a value of 0.  

Typically the Pascal's Triangle's top most row is row zero and defined to be the single value 1.  This definition makes it align with the coefficients found in a binomial expansion, (x +y)^n.  This [wikipedia](https://en.wikipedia.org/wiki/Pascal%27s_triangle) article lays everything out quite well.  

I suggest that the row zero test be deleted.  Community solutions I see are mostly doing a special check to generate a row "zero"  for this test.  

Since C is zero indexed, the indexed positions people use align nicely with the actual definition.  I would say that rows in this exercise refer to the *number of rows* to be generated for the triangle and we wouldn't adjust that definition.  

I image this test was supposed to remind participants to deal with zero values.  I think returning NULL or an error would be more appropriate.  

If you would like a PR to deleted this test, let me know.

**Comment by siebenschlaefer** [comment]
The parameter `rows` for the function `create_triangle(size_t rows)` means: "give me that many rows", so `create_triangle(3)` means "give me three rows", and `create_triangle(0)` means "give me zero rows". I think that makes sense.

The instructions and the language-independent tests are maintained in a different repository: [problem-specifications](https://github.com/exercism/problem-specifications/tree/main/exercises/pascals-triangle). If you want to modify them I'd suggest discussing that in the [forum](https://forum.exercism.org/c/exercism/bugs-and-features/126) first and reaching a consensus.

**Comment by elmq0022** [comment]
@siebenschlaefer I agree with your first paragraph above.   

The issue I wanted to call out is that `create_triangle(0)`  should be undefined / null and not 0 as the test defines it.  I guess modifying the instructions to say return 0 for an undefined triangle would work.
