### ISSUE TITLE
pig latin  in C track

### ISSUE THREAD

**Issue by EmVee381** [exercism/c#952]
i have noticed inconsistency between rule 3
`
Rule 3: If a word starts with a consonant sound followed by "qu", move it to the end of the word, and then add an "ay" sound to the end of the word (e.g. "square" -> "aresquay").
`

and test
```
static void test_word_beginning_with_qu(void)
{
   TEST_IGNORE();
   check_transate("queen", "eenquay");
}
``` 
i a not native english speaker, but if i follow the rule, i would not expect it describe also state when "qu" is in the beginning of the word as there is said "consonant sound followed by "qu" "
but if i asked chatgpt it also understood it same as me and skipped state for rords beginning with "qu"

**Comment by siebenschlaefer** [comment]
In the example the "consonant sound" is "s", followed by "qu".  
In the test there is no such "consonant sound" becore "qu", therefore this rule 3 does not apply.

But this is not the right repository for the issue, the C track takes its test cases from the language-indepentent [problem-specification](https://github.com/exercism/problem-specifications). If you want to discuss the description and/or propose changes please do that on the [forum](https://forum.exercism.org/c/exercism/4).

**Comment by EmVee381** [comment]
ok i have created this issue in problem specifiaction repository, thanks
