### ISSUE TITLE
Return type for `convert(char result[], int drops)` in "Raindrop" should be of type `void`

### ISSUE THREAD

**Issue by Ashvith10** [exercism/c#968]
Since the test cases do not make use of returned value, and it is clear from the overview that the argument is used to pass the string by reference, it makes sense to use `void` instead. Learners might be confuse this behavior.

**Comment by wolf99** [comment]
I'm ok with this.
Would you like to make a PR with this change @Ashvith10 ?

**Comment by Ashvith10** [comment]
@wolf99 I've created a PR for the same.
